model:
    name: 'SelfSupModel'
    optimizer:
        name: 'Adam'
        depth:
            lr: 0.0002
        pose:
            lr: 0.0002
    scheduler:
        name: 'StepLR'
        step_size: 30
        gamma: 0.5
    depth_net:
        name: 'PackNet01'
        version: '1A'
    pose_net:
        name: 'PoseNet'
        version: ''
    params:
        crop: 'garg'
        min_depth: 0.0
        max_depth: 80.0
datasets:
    augmentation:
        image_shape: (192, 640)
    train:
        batch_size: 1
        dataset: ['KITTI']
        path: ['/media/yoko/SSD-PGU3/workspace/datasets/KITTI/KITTI_raw']
        split: ['data_splits/eigen_zhou_files.txt']
        depth_type: ['velodyne']
        repeat: [2]
    validation:
        dataset: ['KITTI']
        path: ['/media/yoko/SSD-PGU3/workspace/datasets/KITTI/KITTI_raw']
        split: ['data_splits/eigen_val_files.txt',
                'data_splits/eigen_test_files.txt']
        depth_type: ['velodyne']
    test:
        dataset: ['KITTI']
        path: ['/media/yoko/SSD-PGU3/workspace/datasets/KITTI/KITTI_raw']
        split: ['data_splits/eigen_test_files.txt']
        depth_type: ['velodyne']
    # train:
    #     batch_size: 1
    #     dataset: ['KITTI']
    #     path: ['/media/yoko/SSD-PGU3/workspace/datasets/KITTI/monodepth/KITTI_tiny']
    #     split: ['kitti_tiny.txt']
    #     depth_type: ['velodyne']
    #     repeat: [2]
    # validation:
    #     dataset: ['KITTI']
    #     path: ['/media/yoko/SSD-PGU3/workspace/datasets/KITTI/monodepth/KITTI_tiny']
    #     split: ['kitti_tiny.txt']
    #     depth_type: ['velodyne']
    # test:
    #     dataset: ['KITTI']
    #     path: ['/media/yoko/SSD-PGU3/workspace/datasets/KITTI/monodepth/KITTI_tiny']
    #     split: ['kitti_tiny.txt']
    #     depth_type: ['velodyne']
save:
    folder: 'result/train'

checkpoint:
    filepath: 'result/weights'